title: Quantitative Methods Research Group
email: qmrg.rgs.ibg@gmail.com
description: The official website for the RGS-IBG Quantitative Methods Research Group.
twitter_username: qmrg_rgs_ibg
github_username: qmrg

name: Quantitative Methods Research Group
markdown: kramdown
theme: jekyll-theme-cayman
