theme: jekyll-theme-cayman
markdown: kramdown

title: QMRG
description: The official website of the RGS-IBG Quantitative Methods Research Group.
baseurl: "/"
url: https://qmrg.github.io

twitter_username: qmrg_rgs_ibg
github_username: qmrg

permalink: /blog/:year/:month/:day/:title
